<?php

namespace Remorhaz\UniLex\RegExp\Grammar;

use Remorhaz\UniLex\TokenMatcherTemplate;

return [
    'class' => 'Remorhaz\UniLex\RegExp\Grammar\TokenMatcher',
    'template_class' => TokenMatcherTemplate::class,
    'use' => [
        TokenAttribute::class,
        TokenType::class,
    ],
    'on_error' => [
        "if (\$context->getBuffer()->isEnd()) {",
        "    return false;",
        "}",
        "\$char = \$context->getBuffer()->getSymbol();",
        "\$context->getBuffer()->nextSymbol();",
        "\$context",
        "   ->setNewToken(TokenType::INVALID)",
        "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        "return true;",
    ],
    'token_list' => [
        '[\\u0000-\\u001F]' => [
            TokenType::CTL_ASCII,
            "\$context",
            "   ->setNewToken(TokenType::CTL_ASCII)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '[ -#%-\'/:->@_~`]' => [
            TokenType::PRINTABLE_ASCII_OTHER,
            "\$context",
            "   ->setNewToken(TokenType::PRINTABLE_ASCII_OTHER)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\$' => [
            TokenType::DOLLAR,
            "\$context",
            "   ->setNewToken(TokenType::DOLLAR)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\(' => [
            TokenType::LEFT_BRACKET,
            "\$context",
            "   ->setNewToken(TokenType::LEFT_BRACKET)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\)' => [
            TokenType::RIGHT_BRACKET,
            "\$context",
            "   ->setNewToken(TokenType::RIGHT_BRACKET)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\*' => [
            TokenType::STAR,
            "\$context",
            "   ->setNewToken(TokenType::STAR)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\+' => [
            TokenType::PLUS,
            "\$context",
            "   ->setNewToken(TokenType::PLUS)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        ',' => [
            TokenType::COMMA,
            "\$context",
            "   ->setNewToken(TokenType::COMMA)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '-' => [
            TokenType::HYPHEN,
            "\$context",
            "   ->setNewToken(TokenType::HYPHEN)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\.' => [
            TokenType::DOT,
            "\$context",
            "   ->setNewToken(TokenType::DOT)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '0' => [
            TokenType::DIGIT_ZERO,
            "\$context",
            "   ->setNewToken(TokenType::DIGIT_ZERO)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char)",
            "   ->setTokenAttribute(TokenAttribute::DIGIT, chr(\$char));",
        ],
        '[1-7]' => [
            TokenType::DIGIT_OCT,
            "\$context",
            "   ->setNewToken(TokenType::DIGIT_OCT)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char)",
            "   ->setTokenAttribute(TokenAttribute::DIGIT, chr(\$char));",
        ],
        '[8-9]' => [
            TokenType::DIGIT_DEC,
            "\$context",
            "   ->setNewToken(TokenType::DIGIT_DEC)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char)",
            "   ->setTokenAttribute(TokenAttribute::DIGIT, chr(\$char));",
        ],
        '\\?' => [
            TokenType::QUESTION,
            "\$context",
            "   ->setNewToken(TokenType::QUESTION)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '[A-Fa-bd-f]' => [
            TokenType::OTHER_HEX_LETTER,
            "\$context",
            "   ->setNewToken(TokenType::OTHER_HEX_LETTER)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char)",
            "   ->setTokenAttribute(TokenAttribute::DIGIT, chr(\$char));",
        ],
        '[G-OQ-Zg-nq-tvwyz]' => [
            TokenType::OTHER_ASCII_LETTER,
            "\$context",
            "   ->setNewToken(TokenType::OTHER_ASCII_LETTER)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        'P' => [
            TokenType::CAPITAL_P,
            "\$context",
            "   ->setNewToken(TokenType::CAPITAL_P)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\[' => [
            TokenType::LEFT_SQUARE_BRACKET,
            "\$context",
            "   ->setNewToken(TokenType::LEFT_SQUARE_BRACKET)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\\\' => [
            TokenType::BACKSLASH,
            "\$context",
            "   ->setNewToken(TokenType::BACKSLASH)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\]' => [
            TokenType::RIGHT_SQUARE_BRACKET,
            "\$context",
            "   ->setNewToken(TokenType::RIGHT_SQUARE_BRACKET)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\^' => [
            TokenType::CIRCUMFLEX,
            "\$context",
            "   ->setNewToken(TokenType::CIRCUMFLEX)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        'c' => [
            TokenType::SMALL_C,
            "\$context",
            "   ->setNewToken(TokenType::SMALL_C)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char)",
            "   ->setTokenAttribute(TokenAttribute::DIGIT, chr(\$char));",
        ],
        'o' => [
            TokenType::SMALL_O,
            "\$context",
            "   ->setNewToken(TokenType::SMALL_O)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        'p' => [
            TokenType::SMALL_P,
            "\$context",
            "   ->setNewToken(TokenType::SMALL_P)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        'u' => [
            TokenType::SMALL_U,
            "\$context",
            "   ->setNewToken(TokenType::SMALL_U)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        'x' => [
            TokenType::SMALL_X,
            "\$context",
            "   ->setNewToken(TokenType::SMALL_X)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\{' => [
            TokenType::LEFT_CURLY_BRACKET,
            "\$context",
            "   ->setNewToken(TokenType::LEFT_CURLY_BRACKET)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\|' => [
            TokenType::VERTICAL_LINE,
            "\$context",
            "   ->setNewToken(TokenType::VERTICAL_LINE)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '}' => [
            TokenType::RIGHT_CURLY_BRACKET,
            "\$context",
            "   ->setNewToken(TokenType::RIGHT_CURLY_BRACKET)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '\\u007F' => [
            TokenType::OTHER_ASCII,
            "\$context",
            "   ->setNewToken(TokenType::OTHER_ASCII)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
        '[\\u0080-\\x{10FFFF}]' => [
            TokenType::NOT_ASCII,
            "\$context",
            "   ->setNewToken(TokenType::NOT_ASCII)",
            "   ->setTokenAttribute(TokenAttribute::CODE, \$char);",
        ],
    ],
];
